### ISSUE TITLE
Traccar - replace "deviceId" from api/positions with "name" from api/devices

### ISSUE THREAD

**Issue by wkulesza** [TheTransitClock/transitime#218] opened 2020-11-26 13:06 UTC
**Is your enhancement request to replace an existing functionality within TheTransitClock?**
Currently, traccar module takes the deviceId from traccar to be used in TC, instead of name

**Is your enhancement request related to a problem? Please describe.**
deviceId is the value automatically assigned in traccar. 

**Describe the solution you'd like**
User has the control over "name" parameter in traccar and this value should be used to display within TC.
Vehicle: BusABC

**Additional context**
Two requests should be made to Traccar, in order to store "name" rather than "deviceId". Alternatively, both values can be taken and displayed in the following way: 
Vehicle name: BusABC 
Vehicle id: 12

**Comment by scrudden** [comment] 2020-12-09 17:50
Duplicate of #204

**Closed as completed** 2020-12-09 17:50 UTC

**Comment by wkulesza** [comment] 2020-12-15 13:14
Recent commits by scrudden changed this and now TC returns correct values.
Only requirement is for the user that is used to access Traccar api, to be administrator. This is to be set in the Traccar web app.
